package com.ay.dao_auto;

import com.ay.model_auto.AyRole;
import com.ay.model_auto.AyRoleExample;
import java.util.List;

public interface AyRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_role
     *
     * @mbg.generated
     */
    long countByExample(AyRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_role
     *
     * @mbg.generated
     */
    int insert(AyRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_role
     *
     * @mbg.generated
     */
    int insertSelective(AyRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_role
     *
     * @mbg.generated
     */
    List<AyRole> selectByExample(AyRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_role
     *
     * @mbg.generated
     */
    AyRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AyRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AyRole record);
}