package com.ay.dao_auto;

import com.ay.model_auto.AySchool;
import com.ay.model_auto.AySchoolExample;
import java.util.List;

public interface AySchoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_school
     *
     * @mbg.generated
     */
    long countByExample(AySchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_school
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_school
     *
     * @mbg.generated
     */
    int insert(AySchool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_school
     *
     * @mbg.generated
     */
    int insertSelective(AySchool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_school
     *
     * @mbg.generated
     */
    List<AySchool> selectByExample(AySchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_school
     *
     * @mbg.generated
     */
    AySchool selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_school
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AySchool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_school
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AySchool record);
}