package com.ay.dao_auto;

import com.ay.model_auto.AyStudent;
import com.ay.model_auto.AyStudentExample;
import java.util.List;

public interface AyStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_student
     *
     * @mbg.generated
     */
    long countByExample(AyStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_student
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_student
     *
     * @mbg.generated
     */
    int insert(AyStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_student
     *
     * @mbg.generated
     */
    int insertSelective(AyStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_student
     *
     * @mbg.generated
     */
    List<AyStudent> selectByExample(AyStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_student
     *
     * @mbg.generated
     */
    AyStudent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_student
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AyStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_student
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AyStudent record);
}