package com.ay.dao_auto;

import com.ay.model_auto.AyUserAddress;
import com.ay.model_auto.AyUserAddressExample;
import java.util.List;

public interface AyUserAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_user_address
     *
     * @mbg.generated
     */
    long countByExample(AyUserAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_user_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_user_address
     *
     * @mbg.generated
     */
    int insert(AyUserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_user_address
     *
     * @mbg.generated
     */
    int insertSelective(AyUserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_user_address
     *
     * @mbg.generated
     */
    List<AyUserAddress> selectByExample(AyUserAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_user_address
     *
     * @mbg.generated
     */
    AyUserAddress selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_user_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AyUserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_user_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AyUserAddress record);
}