package com.ay.model_auto;

public class AyStudent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ay_student.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ay_student.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ay_student.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ay_student.school_id
     *
     * @mbg.generated
     */
    private Long schoolId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_student
     *
     * @mbg.generated
     */
    public AyStudent(Long id, String name, Integer age, Long schoolId) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_student
     *
     * @mbg.generated
     */
    public AyStudent() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ay_student.id
     *
     * @return the value of ay_student.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ay_student.id
     *
     * @param id the value for ay_student.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ay_student.name
     *
     * @return the value of ay_student.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ay_student.name
     *
     * @param name the value for ay_student.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ay_student.age
     *
     * @return the value of ay_student.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ay_student.age
     *
     * @param age the value for ay_student.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ay_student.school_id
     *
     * @return the value of ay_student.school_id
     *
     * @mbg.generated
     */
    public Long getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ay_student.school_id
     *
     * @param schoolId the value for ay_student.school_id
     *
     * @mbg.generated
     */
    public void setSchoolId(Long schoolId) {
        this.schoolId = schoolId;
    }
}