package com.ay.model_auto;

public class AyUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ay_user.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ay_user.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ay_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ay_user.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ay_user.address_id
     *
     * @mbg.generated
     */
    private Long addressId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_user
     *
     * @mbg.generated
     */
    public AyUser(Long id, String name, String password, Integer age, Long addressId) {
        this.id = id;
        this.name = name;
        this.password = password;
        this.age = age;
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_user
     *
     * @mbg.generated
     */
    public AyUser() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ay_user.id
     *
     * @return the value of ay_user.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ay_user.id
     *
     * @param id the value for ay_user.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ay_user.name
     *
     * @return the value of ay_user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ay_user.name
     *
     * @param name the value for ay_user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ay_user.password
     *
     * @return the value of ay_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ay_user.password
     *
     * @param password the value for ay_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ay_user.age
     *
     * @return the value of ay_user.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ay_user.age
     *
     * @param age the value for ay_user.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ay_user.address_id
     *
     * @return the value of ay_user.address_id
     *
     * @mbg.generated
     */
    public Long getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ay_user.address_id
     *
     * @param addressId the value for ay_user.address_id
     *
     * @mbg.generated
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }
}