package com.ay.model_auto;

public class AyUserRoleRel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ay_user_role_rel.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ay_user_role_rel.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ay_user_role_rel.role_id
     *
     * @mbg.generated
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_user_role_rel
     *
     * @mbg.generated
     */
    public AyUserRoleRel(Long id, Long userId, Long roleId) {
        this.id = id;
        this.userId = userId;
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ay_user_role_rel
     *
     * @mbg.generated
     */
    public AyUserRoleRel() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ay_user_role_rel.id
     *
     * @return the value of ay_user_role_rel.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ay_user_role_rel.id
     *
     * @param id the value for ay_user_role_rel.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ay_user_role_rel.user_id
     *
     * @return the value of ay_user_role_rel.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ay_user_role_rel.user_id
     *
     * @param userId the value for ay_user_role_rel.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ay_user_role_rel.role_id
     *
     * @return the value of ay_user_role_rel.role_id
     *
     * @mbg.generated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ay_user_role_rel.role_id
     *
     * @param roleId the value for ay_user_role_rel.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}